#配置版本号 请勿修改!!!
Version: 2.2

#是否只允许控制台执行插件仓库命令
onlyCommandConsole: false
#是否只允许控制台执行插件网络管理命令
onlyNetCommandConsole: false
#是否只允许控制台执行插件文件管理命令
onlyFileCommandConsole: true
#禁止rm -rf的文件夹列表
blacklist:
- 'plugins'
- 'worlds'
#全体重载忽略列表(##请不要删除原有插件##)
ignorelist: 
- 'Yum'
- 'Vault'
- 'iConomy'
- 'GroupManager'
- 'PermissionsEx'
