name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
version: ${project.version}
author: 喵♂呜
website: http://ci.citycraft.cn:8800/jenkins/job/${project.artifactId}/
commands:
  yum:
    description: MC插件仓库
    usage: §6使用§a/yum help§6查看帮助!
    permission: yum.use
    permission-message: §c你没有 <permission> 的权限来执行此命令!
permissions:
  yum.use:
    description: 插件管理系统使用权限!
    default: op
  yum.reload:
    description: 重新载入插件!
    default: op