name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
website: http://ci.citycraft.cn:8800/jenkins/job/${project.artifactId}/
version: ${project.version}

commands:
  yum:
    description: MC插件仓库
    usage: §6使用§a/yum help§6查看帮助!