name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
version: ${project.version}-git-${env.GIT_COMMIT}
author: 喵♂呜
website: ${ciManagement.url}
commands:
  yum:
    description: MC插件仓库
    aliases: [y,apt-get]
    usage: §6使用§a/yum help§6查看帮助!
    permission: yum.use
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  file:
    description: MC文件管理命令
    aliases: [f]
    usage: §6使用§a/file help§6查看帮助!
    permission: file.use
    permission-message: §c你没有 <permission> 的权限来执行此命令!
permissions:
  yum.use:
    description: 插件管理系统使用权限!
    default: op
  yum.delete:
    description: 删除插件命令使用权限!
    default: op
  yum.install:
    description: 安装插件命令使用权限!
    default: op
  yum.list:
    description: 列出已安装插件使用权限!
    default: op
  yum.load:
    description: 载入插件使用权限!
    default: op
  yum.reload:
    description: 重载插件使用权限!
    default: op
  yum.repo:
    description: 插件仓库使用权限!
    default: op
  yum.unload:
    description: 卸载插件使用权限!
    default: op
  yum.update:
    description: 更新插件使用权限!
    default: op
  yum.updateall:
    description: 更新所有插件使用权限!
    default: op
  yum.upgrade:
    description: 升级插件使用权限!
    default: op
  yum.reload:
    description: 重新载入插件!
    default: op